import { useLang, type Lang } from './i18n';

/** UI strings (Spanish / English). Item names and quotes come from the game's own string table. */
const ES = {
  title: 'Diario de la Run',
  'conn.connecting': 'CONECTANDO',
  'conn.companionDown': 'COMPANION DESCONECTADO',
  'conn.retry': 'Reintentando en {s} s — ¿está abierta la app Isaac Companion?',
  'conn.searching': 'Buscando la app Isaac Companion…',
  'conn.connected': 'ISAAC CONECTADO',
  'conn.connectedPaused': 'ISAAC CONECTADO · PAUSA',
  'conn.lastPacket': 'Último paquete {ago}',
  'conn.idle': 'ISAAC ABIERTO · SIN DATOS',
  'conn.idleDetail': 'Empieza o continúa una partida. Si no cambia, comprueba que el mod está activado.',
  'conn.waiting': 'ESPERANDO A ISAAC',
  'conn.waitingDetail': 'Abre The Binding of Isaac con el mod activado.',
  'conn.disconnected': 'ISAAC DESCONECTADO',
  'conn.noData': 'Sin datos {ago}',
  'conn.incompatible': 'Versión del mod incompatible: actualiza el mod y la app.',
  'run.character': 'Personaje',
  'run.floor': 'Piso',
  'run.time': 'Tiempo',
  'run.seed': 'Semilla',
  'run.mode': 'Modo',
  'run.status': 'Estado',
  'run.curses': 'Maldiciones',
  'run.challenge': 'Reto',
  'run.dead': 'Muerte',
  'run.won': 'Victoria',
  'run.exited': 'Guardada / salida',
  'run.none': 'Sin partida en curso.',
  'btn.langTitle': 'Idioma (interfaz y nombres de objetos)',
  'btn.monitor': '2º monitor',
  'btn.exit': 'Salir',
  'btn.monitorTitle': 'Modo segundo monitor (pantalla completa)',
  'btn.support': 'Apoyar',
  'btn.supportTitle': 'Apoya el proyecto (opcional)',
  'support.title': 'Apoyar Isaac Chronicle',
  'support.note': 'Es totalmente opcional: Isaac Chronicle seguirá siendo gratis. ¡Gracias!',
  'support.text': '¿Te resulta útil? Es gratis; si quieres, puedes apoyarlo:',
  'btn.mobile': 'Móvil',
  'btn.mobileTitle': 'Ver la partida en el móvil (misma red Wi-Fi)',
  'mobile.title': 'Ver en el móvil',
  'mobile.intro': 'Activa el modo móvil para abrir esta web en tu móvil o tablet conectado a la misma red Wi-Fi que este PC.',
  'mobile.enable': 'Activar modo móvil',
  'mobile.disable': 'Desactivar modo móvil',
  'mobile.privacy': 'Solo se acepta la red local (no Internet) y cada acceso necesita una clave privada que va dentro del QR.',
  'mobile.step1': 'Conecta el móvil a la misma red Wi-Fi que este PC.',
  'mobile.step2': 'Escanea el código con la cámara del móvil y abre el enlace.',
  'mobile.step3': 'Guárdalo en favoritos o en la pantalla de inicio: la próxima vez entra directamente.',
  'mobile.firewall': 'Si el móvil no carga: en el aviso del Firewall de Windows sobre IsaacCompanion permite el acceso en «Redes privadas».',
  'mobile.secret': 'No compartas este QR: da acceso a tu partida a quien lo tenga en tu red.',
  'mobile.noNetwork': 'No se ha encontrado ninguna red local en este PC (Wi-Fi o cable).',
  'mobile.error': 'No se pudo contactar con el Companion.',
  'stats.title': 'Estadísticas',
  'stats.health': 'Vida',
  'stats.noHearts': 'Sin corazones',
  'stats.healthHidden': '??? — Curse of the Unknown oculta tu vida',
  'stats.damage': 'Daño',
  'stats.tears': 'Lágrimas',
  'stats.range': 'Alcance',
  'stats.shotSpeed': 'Vel. disparo',
  'stats.speed': 'Velocidad',
  'stats.luck': 'Suerte',
  'stats.coins': 'Monedas',
  'stats.bombs': 'Bombas',
  'stats.keys': 'Llaves',
  'stats.note': 'Valores reales del juego. Lágrimas = 30/(FireDelay+1) y alcance = TearRange/40, igual que el HUD.',
  'stats.empty': 'Las estadísticas aparecerán al empezar una partida.',
  'stats.form': 'Forma {n}',
  'hearts.eternal': '{n} eterno',
  'hearts.golden': '{n} dorado(s)',
  'hearts.rotten': '{n} podrido(s)',
  'feat.near': 'OBJETO CERCANO',
  'feat.available': 'OBJETO DISPONIBLE',
  'feat.obtained': 'OBJETO OBTENIDO',
  'feat.cardObtained': 'CARTA OBTENIDA',
  'feat.pillObtained': 'PASTILLA OBTENIDA',
  'feat.pillDiscovered': 'PASTILLA DESCUBIERTA',
  'feat.trinketObtained': 'BARATIJA OBTENIDA',
  'feat.last': 'ÚLTIMO OBJETO',
  'feat.lastCard': 'ÚLTIMA CARTA',
  'feat.lastPill': 'ÚLTIMA PASTILLA',
  'feat.tiles': '{n} casillas',
  'feat.follow': 'seguir al más cercano',
  'feat.chooseOne': 'Elige solo uno',
  'feat.emptyRoom': '{room}: no hay objetos a la vista.',
  'feat.emptyNoRun': 'Cuando te acerques a un objeto, su ficha aparecerá aquí antes de que lo recojas.',
  'room.title': 'En la habitación',
  'room.nothing': 'Nada que recoger aquí.',
  'room.minor': '+{n} recolectables menores (monedas, corazones, cofres…)',
  'room.pin': 'Fijar en la ficha',
  'price.devil': 'Trato del diablo',
  'unknown.collectible': 'Objeto desconocido',
  'unknown.trinket': 'Baratija desconocida',
  'unknown.card': 'Carta desconocida',
  'unknown.pill': 'Pastilla desconocida',
  'unknown.blind': 'Objeto oculto',
  'unknown.blindText': 'El juego oculta este objeto (Curse of the Blind o pedestal con “?”). No se revela para respetar la partida.',
  'unknown.pillText': 'No sabrás qué hace hasta que la tomes.',
  'unknown.cardText': 'Recógela para saber qué es.',
  'unknown.floorText': 'Está en el suelo: recógela para saber qué es.',
  'unknown.farText': 'Acércate para identificarlo.',
  'card.notInDb': 'Objeto no encontrado en la base de datos{mod}. Se puede añadir sin actualizar el mod.',
  'card.notInDbMod': ' (probablemente de otro mod)',
  'card.effects': 'Efectos',
  'card.synergies': 'Sinergias conocidas',
  'card.withYour': 'Con tu {name}:',
  'card.noOwnedSyn': 'Ninguna con tu inventario actual.',
  'card.text': 'Texto',
  'card.textLang': '(en inglés, CC BY-SA 4.0)',
  'card.quality': 'Calidad {q} de 4',
  'card.transformation': 'Cuenta para esta transformación',
  'card.pools': 'Pools',
  'card.close': 'Cerrar',
  'cache.damage': 'Daño',
  'cache.firedelay': 'Lágrimas',
  'cache.range': 'Alcance',
  'cache.shotspeed': 'Vel. disparo',
  'cache.speed': 'Velocidad',
  'cache.luck': 'Suerte',
  'cache.flying': 'Vuelo',
  'cache.familiars': 'Familiares',
  'cache.tearflag': 'Efecto de lágrima',
  'cache.all': 'Varias stats',
  'kind.collectible': 'Objeto',
  'kind.trinket': 'Baratija',
  'kind.card': 'Carta',
  'kind.pill': 'Pastilla',
  'type.passive': 'Pasivo',
  'type.active': 'Activo',
  'type.familiar': 'Familiar',
  'type.trinket': 'Baratija',
  'type.tarot': 'Tarot',
  'type.tarot_reverse': 'Tarot invertido',
  'type.suit': 'Carta de palo',
  'type.rune': 'Runa',
  'type.special': 'Carta especial',
  'type.object': 'Objeto de bolsillo',
  'inv.title': 'Inventario',
  'inv.empty': 'Todavía no has recogido objetos.',
  'inv.active': 'Activo',
  'inv.active2': 'Activo 2',
  'inv.pocket': 'Bolsillo',
  'inv.pocket2': 'Bolsillo 2',
  'inv.golden': 'Dorada',
  'inv.trinket': 'Baratija',
  'inv.card': 'Carta',
  'inv.pill': 'Pastilla',
  'inv.cardNoId': 'El juego no ha dado su identificador',
  'inv.pillHint': 'Se descubrirá al tomarla',
  'syn.title': 'Sinergias activas',
  'syn.empty': 'Sin sinergias conocidas entre tus objetos (fuente: wiki, CC BY-SA 4.0).',
  'syn.source': 'fuente',
  'hist.title': 'Historial de la run',
  'hist.events': 'Eventos',
  'hist.all': 'Todo',
  'hist.empty': 'La línea temporal empieza con la partida.',
  'hist.run_started': 'RUN INICIADA',
  'hist.run_continued': 'RUN CONTINUADA',
  'hist.floor_changed': 'NUEVO PISO',
  'hist.room_changed': 'CAMBIO DE SALA',
  'hist.item_found': 'OBJETO ENCONTRADO',
  'hist.item_picked': 'OBJETO RECOGIDO',
  'hist.stats_changed': 'STATS',
  'hist.transformation': 'TRANSFORMACIÓN',
  'hist.discovered': '¡NUEVO DESCUBRIMIENTO!',
  'hist.consumable_used': 'USADO',
  'hist.run_won': 'VICTORIA',
  'hist.run_lost': 'MUERTE',
  'hist.run_exited': 'SALIDA',
  'map.title': 'Mapa',
  'map.empty': 'El mapa se dibuja a medida que exploras.',
  'map.offgrid': 'fuera del mapa ({room})',
  'map.current': 'actual',
  'map.visited': 'visitada',
  'map.seen': 'vista',
  'map.unvisited': ' (sin visitar)',
  'map.amnesia': 'Amnesia: has olvidado el mapa de este piso.',
  'map.lost': 'Curse of the Lost: el mapa está oculto en este piso.',
  'popup.available': 'OBJETO DISPONIBLE',
  'tab.run': 'Run',
  'tab.inventory': 'Inventario',
  'tab.synergies': 'Sinergias',
  'tab.history': 'Historial',
  'tab.map': 'Mapa',
  'ago.now': 'ahora',
  'ago.s': 'hace {n} s',
  'ago.min': 'hace {n} min',
  'ago.h': 'hace {n} h',
  'floor.n': 'Piso {n}',
  'welcome.title': 'Cómo empezar',
  'welcome.lead':
    '{name} muestra tu partida de The Binding of Isaac en tiempo real: stats, objetos al acercarte, inventario, sinergias, mapa e historial. Nada se dibuja dentro del juego.',
  'welcome.step1': 'Suscríbete al mod',
  'welcome.step1b': 'en Steam Workshop',
  'welcome.openSteam': 'abrir en Steam',
  'welcome.search': 'busca “{name}”',
  'welcome.step2': 'Descarga y abre Isaac Chronicle Companion',
  'welcome.step2b': 'Es un único .exe: déjalo abierto mientras juegas.',
  'welcome.step3': 'Inicia Isaac',
  'welcome.step3b': 'y empieza o continúa una partida.',
  'welcome.detected': '✓ detectado',
  'welcome.connected': '✓ conectado',
  'welcome.note':
    'Esta página se conecta a la app en tu propio PC ({addr}); tus datos no salen de tu ordenador. Si el navegador pregunta por el acceso a la red local, permítelo. También puedes abrir directamente',
  'welcome.code': 'Código y documentación en GitHub',
  'welcome.lang': 'Interfaz en castellano e inglés: botón ES/EN arriba a la derecha.',
};

type Key = keyof typeof ES;

const EN: Record<Key, string> = {
  title: 'Run Journal',
  'conn.connecting': 'CONNECTING',
  'conn.companionDown': 'COMPANION OFFLINE',
  'conn.retry': 'Retrying in {s} s — is the Isaac Companion app open?',
  'conn.searching': 'Looking for the Isaac Companion app…',
  'conn.connected': 'ISAAC CONNECTED',
  'conn.connectedPaused': 'ISAAC CONNECTED · PAUSED',
  'conn.lastPacket': 'Last packet {ago}',
  'conn.idle': 'ISAAC OPEN · NO DATA',
  'conn.idleDetail': 'Start or continue a run. If this does not change, check that the mod is enabled.',
  'conn.waiting': 'WAITING FOR ISAAC',
  'conn.waitingDetail': 'Open The Binding of Isaac with the mod enabled.',
  'conn.disconnected': 'ISAAC DISCONNECTED',
  'conn.noData': 'No data {ago}',
  'conn.incompatible': 'Incompatible mod version: update the mod and the app.',
  'run.character': 'Character',
  'run.floor': 'Floor',
  'run.time': 'Time',
  'run.seed': 'Seed',
  'run.mode': 'Mode',
  'run.status': 'Status',
  'run.curses': 'Curses',
  'run.challenge': 'Challenge',
  'run.dead': 'Death',
  'run.won': 'Victory',
  'run.exited': 'Saved / exited',
  'run.none': 'No run in progress.',
  'btn.langTitle': 'Language (interface and item names)',
  'btn.monitor': '2nd monitor',
  'btn.exit': 'Exit',
  'btn.monitorTitle': 'Second monitor mode (fullscreen)',
  'btn.support': 'Support',
  'btn.supportTitle': 'Support the project (optional)',
  'support.title': 'Support Isaac Chronicle',
  'support.note': 'Completely optional: Isaac Chronicle will stay free. Thank you!',
  'support.text': 'Find it useful? It is free; if you like, you can support it:',
  'btn.mobile': 'Mobile',
  'btn.mobileTitle': 'Follow the run on your phone (same Wi-Fi)',
  'mobile.title': 'View on your phone',
  'mobile.intro': 'Turn on mobile mode to open this page on a phone or tablet connected to the same Wi-Fi network as this PC.',
  'mobile.enable': 'Turn on mobile mode',
  'mobile.disable': 'Turn off mobile mode',
  'mobile.privacy': 'Only the local network is accepted (not the Internet) and every access needs a private key carried by the QR code.',
  'mobile.step1': 'Connect your phone to the same Wi-Fi network as this PC.',
  'mobile.step2': 'Scan the code with the phone camera and open the link.',
  'mobile.step3': 'Bookmark it or add it to the home screen: next time open it directly.',
  'mobile.firewall': 'If the phone cannot load it: in the Windows Firewall prompt about IsaacCompanion, allow access on "Private networks".',
  'mobile.secret': 'Do not share this QR code: anyone on your network who has it can see your run.',
  'mobile.noNetwork': 'No local network was found on this PC (Wi-Fi or cable).',
  'mobile.error': 'Could not reach the Companion.',
  'stats.title': 'Stats',
  'stats.health': 'Health',
  'stats.noHearts': 'No hearts',
  'stats.healthHidden': '??? — Curse of the Unknown hides your health',
  'stats.damage': 'Damage',
  'stats.tears': 'Tears',
  'stats.range': 'Range',
  'stats.shotSpeed': 'Shot speed',
  'stats.speed': 'Speed',
  'stats.luck': 'Luck',
  'stats.coins': 'Coins',
  'stats.bombs': 'Bombs',
  'stats.keys': 'Keys',
  'stats.note': 'Real in-game values. Tears = 30/(FireDelay+1) and range = TearRange/40, same as the HUD.',
  'stats.empty': 'Stats will appear when a run starts.',
  'stats.form': 'Form {n}',
  'hearts.eternal': '{n} eternal',
  'hearts.golden': '{n} golden',
  'hearts.rotten': '{n} rotten',
  'feat.near': 'NEARBY ITEM',
  'feat.available': 'ITEM AVAILABLE',
  'feat.obtained': 'ITEM OBTAINED',
  'feat.cardObtained': 'CARD OBTAINED',
  'feat.pillObtained': 'PILL OBTAINED',
  'feat.pillDiscovered': 'PILL DISCOVERED',
  'feat.trinketObtained': 'TRINKET OBTAINED',
  'feat.last': 'LAST ITEM',
  'feat.lastCard': 'LAST CARD',
  'feat.lastPill': 'LAST PILL',
  'feat.tiles': '{n} tiles',
  'feat.follow': 'follow nearest',
  'feat.chooseOne': 'Choose only one',
  'feat.emptyRoom': '{room}: no items in sight.',
  'feat.emptyNoRun': 'When you get close to an item, its card will appear here before you pick it up.',
  'room.title': 'In this room',
  'room.nothing': 'Nothing to pick up here.',
  'room.minor': '+{n} minor pickups (coins, hearts, chests…)',
  'room.pin': 'Pin to the card',
  'price.devil': 'Devil deal',
  'unknown.collectible': 'Unknown item',
  'unknown.trinket': 'Unknown trinket',
  'unknown.card': 'Unknown card',
  'unknown.pill': 'Unknown pill',
  'unknown.blind': 'Hidden item',
  'unknown.blindText': 'The game hides this item (Curse of the Blind or “?” pedestal). It is not revealed, to respect the run.',
  'unknown.pillText': 'You will not know what it does until you take it.',
  'unknown.cardText': 'Pick it up to find out what it is.',
  'unknown.floorText': 'It is on the floor: pick it up to find out what it is.',
  'unknown.farText': 'Get closer to identify it.',
  'card.notInDb': 'Item not found in the database{mod}. It can be added without updating the mod.',
  'card.notInDbMod': ' (probably from another mod)',
  'card.effects': 'Effects',
  'card.synergies': 'Known synergies',
  'card.withYour': 'With your {name}:',
  'card.noOwnedSyn': 'None with your current inventory.',
  'card.text': 'Text',
  'card.textLang': '(CC BY-SA 4.0)',
  'card.quality': 'Quality {q} of 4',
  'card.transformation': 'Counts toward this transformation',
  'card.pools': 'Pools',
  'card.close': 'Close',
  'cache.damage': 'Damage',
  'cache.firedelay': 'Tears',
  'cache.range': 'Range',
  'cache.shotspeed': 'Shot speed',
  'cache.speed': 'Speed',
  'cache.luck': 'Luck',
  'cache.flying': 'Flight',
  'cache.familiars': 'Familiars',
  'cache.tearflag': 'Tear effect',
  'cache.all': 'Several stats',
  'kind.collectible': 'Item',
  'kind.trinket': 'Trinket',
  'kind.card': 'Card',
  'kind.pill': 'Pill',
  'type.passive': 'Passive',
  'type.active': 'Active',
  'type.familiar': 'Familiar',
  'type.trinket': 'Trinket',
  'type.tarot': 'Tarot',
  'type.tarot_reverse': 'Reversed tarot',
  'type.suit': 'Suit card',
  'type.rune': 'Rune',
  'type.special': 'Special card',
  'type.object': 'Pocket object',
  'inv.title': 'Inventory',
  'inv.empty': 'You have not picked up any items yet.',
  'inv.active': 'Active',
  'inv.active2': 'Active 2',
  'inv.pocket': 'Pocket',
  'inv.pocket2': 'Pocket 2',
  'inv.golden': 'Golden',
  'inv.trinket': 'Trinket',
  'inv.card': 'Card',
  'inv.pill': 'Pill',
  'inv.cardNoId': 'The game gave no id',
  'inv.pillHint': 'Revealed when you take it',
  'syn.title': 'Active synergies',
  'syn.empty': 'No known synergies between your items (source: wiki, CC BY-SA 4.0).',
  'syn.source': 'source',
  'hist.title': 'Run history',
  'hist.events': 'Events',
  'hist.all': 'All',
  'hist.empty': 'The timeline starts with the run.',
  'hist.run_started': 'RUN STARTED',
  'hist.run_continued': 'RUN CONTINUED',
  'hist.floor_changed': 'NEW FLOOR',
  'hist.room_changed': 'ROOM CHANGED',
  'hist.item_found': 'ITEM FOUND',
  'hist.item_picked': 'ITEM PICKED',
  'hist.stats_changed': 'STATS',
  'hist.transformation': 'TRANSFORMATION',
  'hist.discovered': 'NEW DISCOVERY!',
  'hist.consumable_used': 'USED',
  'hist.run_won': 'VICTORY',
  'hist.run_lost': 'DEATH',
  'hist.run_exited': 'EXITED',
  'map.title': 'Map',
  'map.empty': 'The map is drawn as you explore.',
  'map.offgrid': 'off the map ({room})',
  'map.current': 'current',
  'map.visited': 'visited',
  'map.seen': 'seen',
  'map.unvisited': ' (not visited)',
  'map.amnesia': 'Amnesia: you forgot the map of this floor.',
  'map.lost': 'Curse of the Lost: the map is hidden on this floor.',
  'popup.available': 'ITEM AVAILABLE',
  'tab.run': 'Run',
  'tab.inventory': 'Inventory',
  'tab.synergies': 'Synergies',
  'tab.history': 'History',
  'tab.map': 'Map',
  'ago.now': 'just now',
  'ago.s': '{n} s ago',
  'ago.min': '{n} min ago',
  'ago.h': '{n} h ago',
  'floor.n': 'Floor {n}',
  'welcome.title': 'Getting started',
  'welcome.lead':
    '{name} shows your Binding of Isaac run in real time: stats, items as you get close, inventory, synergies, map and history. Nothing is drawn in-game.',
  'welcome.step1': 'Subscribe to the mod',
  'welcome.step1b': 'on Steam Workshop',
  'welcome.openSteam': 'open in Steam',
  'welcome.search': 'search for “{name}”',
  'welcome.step2': 'Download and open Isaac Chronicle Companion',
  'welcome.step2b': 'It is a single .exe: keep it open while you play.',
  'welcome.step3': 'Start Isaac',
  'welcome.step3b': 'and start or continue a run.',
  'welcome.detected': '✓ detected',
  'welcome.connected': '✓ connected',
  'welcome.note':
    'This page connects to the app on your own PC ({addr}); your data never leaves your computer. If the browser asks for local network access, allow it. You can also open directly',
  'welcome.code': 'Code and documentation on GitHub',
  'welcome.lang': 'Interface in English and Spanish: ES/EN button at the top right.',
};

const DICT: Record<Lang, Record<Key, string>> = { es: ES, en: EN };

export type T = (key: Key, vars?: Record<string, string | number>) => string;

export function translate(lang: Lang, key: Key, vars?: Record<string, string | number>): string {
  let s = DICT[lang][key] ?? ES[key] ?? key;
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.replace(`{${k}}`, String(v));
  return s;
}

export function useT(): T {
  const lang = useLang();
  return (key, vars) => translate(lang, key, vars);
}

/** Default language: saved choice, else the browser's (Spanish if it starts with "es"). */
export function defaultLang(saved: string | null): Lang {
  if (saved === 'es' || saved === 'en') return saved;
  return typeof navigator !== 'undefined' && navigator.language?.toLowerCase().startsWith('es') ? 'es' : 'en';
}
